### ISSUE TITLE
Кастомная директория скинов и плащей

### ISSUE THREAD

**Issue by UrbanSide** [NC22/Minecraft-HD-skin-viewer-2D#6]
Как можно сделать чтобы например плащи были в cloak а скины в skins? И он их тягал оттуда?
И реально ли?

**Comment by UrbanSide** [comment]
```
    require getcwd().'/SkinViewer2D.class.php';
    header("Content-type: image/png");

    $show = $_GET['show'];
    $skin = isset($_GET['hd']) ? './skins/skin/uside.png' : './skin.png';
    $cloak = isset($_GET['cloak']) ? (($_GET['cloak'] === 'hd') ? './skins/cape/uside.png' : './cloak.png') : false;
    $side = isset($_GET['side']) ? $_GET['side'] : false;

    $img = skinViewer2D::createPreview($skin, $cloak, $side);
    

    imagepng($img);
```

Делал так но ловлю ошибку


```
[01-Oct-2023 21:54:38 Europe/Moscow] PHP Fatal error:  Uncaught TypeError: imagepng(): Argument #1 ($image) must be of type GdImage, bool given in C:\WebOSPanel\domains\game.smoll.net\skinshd\skinTest.php:16
Stack trace:
#0 C:\WebOSPanel\domains\game.smoll.net\skinshd\skinTest.php(16): imagepng()
#1 {main}
  thrown in C:\WebOSPanel\domains\game.smoll.net\skinshd\skinTest.php on line 16
```

**Comment by UrbanSide** [comment]
```
string(21) "./data/skin/uside.png" bool(false) Версия GD: bundled (2.1.0 compatible)
Fatal error: Uncaught TypeError: imagepng(): Argument #1 ($image) must be of type GdImage, bool given in C:\WebOSPanel\domains\game.smoll.net\skinshd\skinTest.php:17 Stack trace: #0 C:\WebOSPanel\domains\game.smoll.net\skinshd\skinTest.php(17): imagepng() #1 {main} thrown in C:\WebOSPanel\domains\game.smoll.net\skinshd\skinTest.php on line 17
```
